### ISSUE TITLE
 Custom Record Label not shown

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-extended-reports#1]
Dear Luke,
thanks for this great module!
I guess there is some reason behind that, but would be nice to have also the Custom Record Label next to the Record.
This is not always shown in report.
Furthermore, if data are not saved in an event and the report should show variables belonging to this event, the record field is not shown.
I guess these two points are linked together
![image](https://github.com/lsgs/redcap-extended-reports/assets/75424115/0602998f-a4ae-4825-8575-841abc43eca9)

best
Thomas

**Comment by lsgs** [comment]
Thanks for reporting @ThomasVermes. There is indeed something amiss with the custom record label where it seems to sometimes work and sometimes not. I have also just seen another report that has blank rows like that. Investigating...

**Comment by lsgs** [comment]
@ThomasVermes, these issues should be fixed now with release 2.0.1
