### ISSUE TITLE
TypeError in REDCap after upgrade to PHP 8.2.12

### ISSUE THREAD

**Issue by Samantao93** [lsgs/redcap-extended-reports#10]
Versions: **REDCap 13.7.22 • PHP 8.2.12 (Linux/Unix OS) • MariaDB 10.6.16**

The 'extended_reports' module threw the following exception when calling the hook method 'redcap_every_page_before_render':

TypeError: **array_key_exists()**: Argument #1 ($key) must be a valid array offset type in /url/modules/extended_reports_v2.0.1/Report.php:1274
Stack trace:
#0 /url/modules/extended_reports_v2.0.1/Report.php(1274): array_key_exists()
#1 /url/modules/extended_reports_v2.0.1/Report.php(1260): MCRI\ExtendedReports\Report->makeChoiceDisplayHtml()
#2 /url/modules/extended_reports_v2.0.1/Report.php(1057): MCRI\ExtendedReports\Report->makeChoiceDisplay()
#3 /url/modules/extended_reports_v2.0.1/Report.php(525): MCRI\ExtendedReports\Report->makeOutputValue()
#4 /url/modules/extended_reports_v2.0.1/Report.php(153): MCRI\ExtendedReports\Report->doExtendedReport()
#5 /url/modules/extended_reports_v2.0.1/ExtendedReports.php(57): MCRI\ExtendedReports\Report->viewReport()
#6 /url/redcap_v13.7.22/ExternalModules/classes/ExternalModules.php(3165): MCRI\ExtendedReports\ExtendedReports->redcap_every_page_before_render()
#7 /url/redcap_v13.7.22/ExternalModules/classes/ExternalModules.php(3330): ExternalModules\ExternalModules::startHook()
#8 /url/redcap_v13.7.22/ExternalModules/classes/ExternalModules.php(3363): ExternalModules\ExternalModules::ExternalModules\{closure}()
#9 /url/redcap_v13.7.22/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook()
#10 /url/redcap_v13.7.22/Classes/System.php(964): Hooks::call()
#11 /url/redcap_v13.7.22/Config/init_project.php(7): System::initProjectPage()
#12 /url/redcap_v13.7.22/DataExport/report_ajax.php(4): require_once('...')
#13 {main}

URL: /url/redcap_v13.7.22/DataExport/report_ajax.php?pid=correct_number_pid&pagenum=1
Server:  our_server
User: proper_user
Project ID: correct_number_pid
Module Name: Extended Reports (extended_reports)
Module Author(s): luke.stevens@mcri.edu.au
Run Time: 1 seconds

**Comment by lsgs** [comment]
I've added a check that the key is not empty at that point, @Samantao93. I think that should fix this issue. Please reopen if you keep getting it in the new release, out soon.
