### ISSUE TITLE
TypeError: array_key_exists(): Argument #2 ($array)

### ISSUE THREAD

**Issue by Samantao93** [lsgs/redcap-extended-reports#13]
REDCap 14.0.7 · PHP 8.2.15 (Linux/Unix OS) · MariaDB 10.6.16

The 'extended_reports' module threw the following exception when calling the hook method 'redcap_every_page_before_render':

**TypeError: array_key_exists(): Argument #2 ($array)** must be of type array, int given in /url/modules/extended_reports_v2.0.1/Report.php:420

Stack trace:

#0 /url/modules/extended_reports_v2.0.1/Report.php(420): array_key_exists()
#1 /url/modules/extended_reports_v2.0.1/ExtendedReports.php(66): MCRI\ExtendedReports\Report->exportReport()
#2 /url/version/ExternalModules/classes/ExternalModules.php(3159): MCRI\ExtendedReports\ExtendedReports->redcap_every_page_before_render()
#3 /url/version/ExternalModules/classes/ExternalModules.php(3326): ExternalModules\ExternalModules::startHook()
#4 /url/version/ExternalModules/classes/ExternalModules.php(3359): ExternalModules\ExternalModules::ExternalModules\{closure}()
#5 /url/version/Classes/Hooks.php(41): ExternalModules\ExternalModules::callHook()
#6 /url/version/Classes/System.php(998): Hooks::call()
#7 /url/version/Config/init_project.php(7): System::initProjectPage()
#8 /url/version/DataExport/data_export_ajax.php(9): require_once('...')
#9 {main}

URL: https://url/version/DataExport/data_export_ajax.php?pid=X&xml_metadata_options=

Module Name: Extended Reports (extended_reports)
Module Author(s): luke.stevens@mcri.edu.au
Run Time: 2 seconds

Thanks for the great work.

**Comment by lsgs** [comment]
Please can you let me know if this issue persists following an upgrade to the new release, v2.1.0, @Samantao93?

**Comment by Samantao93** [comment]
Yes, it seems to be solved. Thank you.
