### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by tikiatua** [lsgs/redcap-extended-reports#16]
Hi @lsgs 

Thank you very much for developing this awesome plugin. We operate a validated REDCap infrastructure at the Department of Clinical Research Basel, Switzerland and I did a quick code review as part of our external module validation. In the course of this, I have found a security issue.

Is there any option to report this to you via a private channel? You can reach me via the contact information on our website: https://dkf.unibas.ch/en/team-application-development/ (Ramon Saccilotto)

**Comment by lsgs** [comment]
I found your email on that link and have sent you a message Ramon (@tikiatua). Thank you for getting in touch.

**Comment by lsgs** [comment]
I have made a change and included it in release v2.1.1: https://github.com/lsgs/redcap-extended-reports/releases/tag/2.1.1
