### ISSUE TITLE
Module causing the deletion of Rapid Retrieval files

### ISSUE THREAD

**Issue by lsgs** [lsgs/redcap-extended-reports#18]
Reported in REDCap Community: https://redcap.vanderbilt.edu/community/post.php?id=210241&comment=224954

Applies to REDCap v14+

**Comment by fom-ds-redcap** [comment]
We've fixed this issue on our local machines, by copying new caching functionality in redcap_vX.X.X/DataExport/report_ajax.php,  and will push our changes for approval.

**Comment by lsgs** [comment]
Implemented in release 2.2.0. Thanks @fom-ds-redcap!
