### ISSUE TITLE
first instrument variables are not displayed

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-extended-reports#24]
Hi Luke,

extended reports will not show variables from the first instrument if that is created manually (and not through import of DD. not sure about this last point)) and if it is not a longitudinal project.

This is caused by a redcap "database quirk" which I'm not sure will be fixed

See: [Community Post]( https://redcap.vumc.org/community/post.php?id=232960).

**Normal report:**
![image](https://github.com/lsgs/redcap-extended-reports/assets/75424115/6d1018da-3d5d-481f-a0f8-4915170a4dde)

**With Extended Reports:**
![image](https://github.com/lsgs/redcap-extended-reports/assets/75424115/69caa6c2-0522-4f90-81a1-942818034db6)

best
Thomas

**Comment by lsgs** [comment]
Fix in release 2.1.8
