### ISSUE TITLE
Exporting error

### ISSUE THREAD

**Issue by pevmtss** [lsgs/redcap-extended-reports#26]
Hiya, I am getting the following error whenever I try to export a report using the EM as CSV  (w/ or w/out labels): **An error occurred in processing the extended properties of this report. The file for download is unmodifed.**

This message should seem to imply that an unmodified version of the rpt should still be able to be exported but nothing happens after this message. Tested with both regular rpt and sql query, same error. 
REDCap 14.3.14 · PHP 8.0.30 (Linux/Unix OS) · MySQL 8.0.28
Error seen on both 2.1.7 and persists after upgrade to 2.1.8 (I think exporting was working in REDCap prior to 14.3.9)

**Comment by lsgs** [comment]
Thanks very much for the report @pevmtss. I have not got up to v14.3 yet, but we will be doing so very soon and I most certainly want this module to work on recent versions. I will try and prioritise an investigation and fix for this.

**Comment by lsgs** [comment]
I've been testing the module with REDCap v14.5.x, @pevmtss, and am not experiencing any problems with the CSV exports. Are you still experiencing the issue? If so, I'm wondering whether it is arising due to some characteristic of your project configuration or your data. Can you provide some more detail please?

**Comment by lsgs** [comment]
Using the system-level setting to skip the certificate check on the internal curl call is a suitable workaround for this issue.

**Comment by pevmtss** [comment]
Amazing! Thanks for all your work on this!
