### ISSUE TITLE
Exporting report as CSV error 

### ISSUE THREAD

**Issue by nadha25** [lsgs/redcap-extended-reports#34]
Hiya, I am getting the following error whenever I try to export a report using the EM as CSV (w/ or w/out labels): **The raw data for this export could not be downloaded therefore it could not be reshaped** on all projects that use the EM.

REDCap v14.6.7 PHP v8.2.20

**Comment by lsgs** [comment]
The end of the message you see is directing you towards a fix, @nadha25. There is an option in the Control Center module settings to have it skip the server certificate check on the internal curl call it does with all exports for reshaped reports. Enable that check and it should fix this issue. (I've altered the message slightly in v2.3.0 to hopefully make this a bit clearer.)
