### ISSUE TITLE
SQL using CASE hangs

### ISSUE THREAD

**Issue by aboulang** [lsgs/redcap-extended-reports#35]
A query like this hangs when saving
    SELECT
        record,
        MAX(CASE WHEN field_name = 'block_number' THEN value END) AS block_number,
        MAX(CASE WHEN field_name = 'submission_date' THEN value END) AS submission_date,
        MAX(CASE WHEN field_name = 'lid' THEN value END) AS lid
    FROM redcap_data
    WHERE project_id = 80
    GROUP BY record, instance

but works if rewritten using IF
    SELECT
        record,
        MAX(IF(field_name = 'block_number', value, NULL)) AS block_number,
        MAX(IF(field_name = 'submission_date', value, NULL)) AS submission_date,
        MAX(IF(field_name = 'lid', value, NULL)) AS type
    FROM redcap_data
    WHERE project_id = 80
    GROUP BY record, instance

**Comment by lsgs** [comment]
I'm not able to replicate this issue @aboulang. That query saves for me just fine. Have you been able to narrow it down any further? Are there any messages in your browser console that provide any indication what's going wrong?

And what versions of module and REDCap are you using? Thanks

**Comment by aboulang** [comment]
@lsgs It was REDCap 14.6.9 · PHP 7.4.33 (Linux/Unix OS) · MySQL 5.7.34 Module version 2.3.1  I suspect now it was some kind of resource issue, maybe storage.

**Comment by lsgs** [comment]
All good @aboulang. Closing
