### ISSUE TITLE
Bug: Minimum/maximum value is 0 for variables with only strictly positive/negative numbers

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-extended-reports#37]
When testing EM version 2.3.1 on REDCap v14.5.21 with PHP 7.4, we noticed a bug when trying to summarize a variable (number or integer) on a repeating instrument:

- Minimum value: when only strictly positive values (i.e. greater than 0) were collected for a record, the minimum value is calculated as 0.
- Maximum value: when only strictly negative values (i.e. less than 0) were collected for a record, the maximum value is calculated as 0.

This seems to be related to the lines of code in Report.php. On the first repeating instance, $thisRecValue is still empty, which is converted to a float with a value of 0 (at least with PHP 7.4).
https://github.com/lsgs/redcap-extended-reports/blob/89c46fba12f65de506560123d4dd69e261009bfc/Report.php#L978
https://github.com/lsgs/redcap-extended-reports/blob/89c46fba12f65de506560123d4dd69e261009bfc/Report.php#L989

Could this please be fixed?

**Comment by lsgs** [comment]
Thanks very much @steentje34. I've merged the PR and done a new release. Look out for v2.3.2 arriving soon. I also made a small tweak so when showing first/last/min/max in report view, it will indicate the aggregation in the column headers.

![image](https://github.com/user-attachments/assets/5bfc93b5-0566-4dd0-90e9-8abee9fe0a4d)
