### ISSUE TITLE
Bug: Minimum/maximum value of date fields is broken

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-extended-reports#39]
Hi @lsgs,

It seems that the bug fix that I proposed to fix #37 (PR #38) broke the calculation of minimum/maximum value of date fields. As it is quite difficult to explain in words what happens, I have added 2 screenshots.

- Mimimum
   ![image](https://github.com/user-attachments/assets/d4f5f802-fc8a-428e-8d04-363d76d33bf5)
- Maximum
   ![image](https://github.com/user-attachments/assets/7e0c7e77-5d51-4a31-9fcc-ea3f0520e7b2)

The source of the issue is that I blindly type casted $thisRecValue as a float, without paying attention whether or not $thisRecValue is numeric or not.
https://github.com/lsgs/redcap-extended-reports/blob/aa47fcdcc8b8f179094448296be05267d32dcff4/Report.php#L979
https://github.com/lsgs/redcap-extended-reports/blob/aa47fcdcc8b8f179094448296be05267d32dcff4/Report.php#L989

To fix the bug that I introduced, I will sumbit a Pull Request later today (after coding and testing are completed).

**Comment by lsgs** [comment]
Merged with thanks, @steentje34
