### ISSUE TITLE
Fields duplicated on report

### ISSUE THREAD

**Issue by jhoitenga** [lsgs/redcap-extended-reports#4]
Hi Luke,

We have enabled this module for a longitudinal project, and we have found that fields are duplicating on the report. The issue seems to be related to our filters. For example, the status field is duplicating but if we remove the status field from our filters, it will resolve the issue.

![image](https://github.com/lsgs/redcap-extended-reports/assets/116404784/17bd3097-03e4-42c8-b086-e8d9935348d1)

![image](https://github.com/lsgs/redcap-extended-reports/assets/116404784/1278a6fb-0c5d-44a0-ad60-ea6cc40cf035)

**Comment by lsgs** [comment]
Thank you @jhoitenga. It was indeed including fields from the filters as output columns. The new release will get this fixed up.
