### ISSUE TITLE
Bug: Ontology fields are always displayed/exported as 'Label (value)'

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-extended-reports#42]
Testing Extended Reports v2.3.1 on REDCap v14.5.26, we discovered that the EM always displays and exports ontology fields as 'Label (value)', regardless of the selected options:

- For displaying a report: ![image](https://github.com/user-attachments/assets/6dd24be3-bb0c-4a3f-9600-45c6c2f2315f)
- For exporting a report: 'CSV (raw data)' vs 'CSV (labels)'

Could this bug be fixed, please?

**Comment by lsgs** [comment]
THanks for reporting @steentje34. This should be fixed in the upcoming release, v2.3.3.
