### ISSUE TITLE
Bug: DataTables warning when displaying report with checkbox on repeating instrument/event

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-extended-reports#5]
A DataTables warning is displayed when a report is displayed in the REDCap UI that meets following conditions:
- The report contains a checkbox on a repeating instrument/event
- In STEP 5, any option (other than '-- default (row per instance) --' or 'Column per instance') is selected for the Instances setting

![image](https://github.com/lsgs/redcap-instance-table/assets/29727779/03bc2e24-5dcc-4bb6-a192-8c9de51576ec)

After clicking the 'OK' button, the report is displayed, but there are more cells in the header of the table than there are in the actual data rows.
The issue seems to have no effect on the CSV exports.

Tested on REDCap 13.1.37 · PHP 7.4.33 (Linux/Unix OS) · MariaDB 10.3.35 · Extended Reports 2.0.1

**Comment by lsgs** [comment]
I've fixed this error by having it force the "Combine checkbox choices" option when using an option other than "column per instance". (And return an empty value for checkbox colomns when using the "max" or "min" options.
