### ISSUE TITLE
Exported data is blank

### ISSUE THREAD

**Issue by monash-redcap** [lsgs/redcap-extended-reports#8]
We have around 28,000 data, with 7 columns, when the SQL report is exported, it shows showing empty CSV file.  When we tried to filter the report with the same SQL query to be 1 data, it was exported fine.

**Comment by lsgs** [comment]
Are you able to provide any details I can use to try and replicate this issue please @monash-redcap? Were there any exception messages sent to your admin mailbox, for example? Or can you construct a simple project XML (with data) and an SQL query that replicates the issue? 

Speculating on what might cause the results to display OK on the web page, but produce an empty CSV file, could there be some charracter encoding issues? Is the file really blank when you view it in a text editor?

**Comment by lsgs** [comment]
I believe this issue is fixed in the 2.1.x releases
